const fieldLabels: Record<string, string> = {
    fullNameTriple: "الاسم الثلاثي",
    universityId: "الرقم الجامعي",
    classNumber: "رقم الصف",
    professorName: "اسم الدكتور",
    programName: "البرنامج",
    programCode: "رمز البرنامج",
    subjectName: "اسم المادة",
    subjectCode: "رمز المادة",
    translationPages: "عدد الصفحات",
    targetLanguage: "لغة الترجمة الهدف",
    deliveryDate: "الموعد النهائي",
    researchFile: "ملف البحث",
    homeWorkFile: "ملف الوظيفة",
    partnersInfo: "معلومات الشركاء",
    isAssignmentShared: "هل الوظيفة مشتركة؟",
    universityName: "اسم الجامعة",
    formattingTemplate: "نموذج التنسيق",
    researchDeliveryDate: "الموعد النهائي",
    projectTitle: "عنوان المشروع",
    specialization: "التخصص",
    expectedPages: "عدد الصفحات المتوقع",
    universityRequirements: "متطلبات الجامعة",
    projectDeliveryDate: "الموعد النهائي",
    supervisorName: "المشرف العلمي",
    supervisorInstructions: "تعليمات المشرف",
    cvFullName: "الاسم",
    cvSpecialization: "التخصص",
    cvExperience: "الخبرات",
    cvSkills: "المهارات",
    cvCourses: "الدورات التدريبية",
    cvLanguages: "اللغات",
    cvObjective: "الهدف المهني",
    presentationTopic: "موضوع العرض",
    presentationSlides: "عدد الشرائح",
    presentationContent: "المحتوى",
    presentationLanguage: "لغة العرض",
    presentationDeliveryDate: "الموعد النهائي",
    posterTitle: "عنوان المشروع",
    posterStudentName: "اسم الطالب",
    posterUniversity: "اسم الجامعة",
    posterLogo: "الشعار",
    posterSize: "المقاس المطلوب",
    surveyTopic: "موضوع البحث",
    surveyTarget: "الفئة المستهدفة",
    surveyQuestionsCount: "عدد الأسئلة",
    surveyQuestionType: "نوع الأسئلة",
    websiteType: "نوع الموقع",
    pagesRequired: "الصفحات المطلوبة",
    technologies: "التقنيات المفضلة",
    hasDesign: "يوجد تصميم جاهز",
    designFile: "ملف التصميم",
    assignmentType: "نوع الوظيفة",
    subject: "الموضوع",
    pagesOrWords: "عدد الصفحات/الكلمات",
    needsReferences: "يحتاج مراجع",
    referenceFile: "ملف المراجع",
    researchTitle: "عنوان البحث",
    methodology: "المنهجية",
    sourceCount: "عدد المصادر",
    citationFormat: "تنسيق الاقتباس",
    
  };
  export const getFieldLabel = (field: string): string => fieldLabels[field] || field;